// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVloWf5hBjiC43HNTu2h65oTYH0KW2XMk',
    appId: '1:613316955342:web:e43d6404c56da3d715149f',
    messagingSenderId: '613316955342',
    projectId: 'kirchesch-public-tests',
    authDomain: 'kirchesch-public-tests.firebaseapp.com',
    storageBucket: 'kirchesch-public-tests.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6NGHD_43KtT5RGNZbaCLEmGd5lFmr6kU',
    appId: '1:613316955342:android:3581440e20ef9cb715149f',
    messagingSenderId: '613316955342',
    projectId: 'kirchesch-public-tests',
    storageBucket: 'kirchesch-public-tests.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJMxyHvT2mMsnx93HLi3r8B_S2R7_Fad0',
    appId: '1:613316955342:ios:e3c66d897ba0299815149f',
    messagingSenderId: '613316955342',
    projectId: 'kirchesch-public-tests',
    storageBucket: 'kirchesch-public-tests.appspot.com',
    iosClientId: '613316955342-m2c875mk82s4kpaou541v81unj6gcrj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseIssues',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJMxyHvT2mMsnx93HLi3r8B_S2R7_Fad0',
    appId: '1:613316955342:ios:e3c66d897ba0299815149f',
    messagingSenderId: '613316955342',
    projectId: 'kirchesch-public-tests',
    storageBucket: 'kirchesch-public-tests.appspot.com',
    iosClientId: '613316955342-m2c875mk82s4kpaou541v81unj6gcrj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseIssues',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVloWf5hBjiC43HNTu2h65oTYH0KW2XMk',
    appId: '1:613316955342:web:a7d7574fea5d0adc15149f',
    messagingSenderId: '613316955342',
    projectId: 'kirchesch-public-tests',
    authDomain: 'kirchesch-public-tests.firebaseapp.com',
    storageBucket: 'kirchesch-public-tests.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAVloWf5hBjiC43HNTu2h65oTYH0KW2XMk',
    appId: '1:613316955342:web:04542d5b61af859c15149f',
    messagingSenderId: '613316955342',
    projectId: 'kirchesch-public-tests',
    authDomain: 'kirchesch-public-tests.firebaseapp.com',
    storageBucket: 'kirchesch-public-tests.appspot.com',
  );
}
